// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqmRHcvqYnGbp3jrYlAOW0ox24XgbsJv0',
    appId: '1:287386333635:web:ae3c5114b053f8198e8d76',
    messagingSenderId: '287386333635',
    projectId: 'shalong-4a203',
    authDomain: 'shalong-4a203.firebaseapp.com',
    storageBucket: 'shalong-4a203.appspot.com',
    measurementId: 'G-2MF6T9E6WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8lpsWG_Mz1h1trx6XDdX_Mm5Ti1e1RYI',
    appId: '1:287386333635:android:b1315fdbbc6f919b8e8d76',
    messagingSenderId: '287386333635',
    projectId: 'shalong-4a203',
    storageBucket: 'shalong-4a203.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWfIiwKzHyVPnL29CKJFjK8c7LY8mT-JQ',
    appId: '1:287386333635:ios:26be113d2fd27e048e8d76',
    messagingSenderId: '287386333635',
    projectId: 'shalong-4a203',
    storageBucket: 'shalong-4a203.appspot.com',
    androidClientId: '287386333635-hp75q0lb33e7bd9kr5j8spsam36q55ln.apps.googleusercontent.com',
    iosClientId: '287386333635-docmlqusnr6t3nedi97llc2n6394nk90.apps.googleusercontent.com',
    iosBundleId: 'com.example.newShalongApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWfIiwKzHyVPnL29CKJFjK8c7LY8mT-JQ',
    appId: '1:287386333635:ios:26be113d2fd27e048e8d76',
    messagingSenderId: '287386333635',
    projectId: 'shalong-4a203',
    storageBucket: 'shalong-4a203.appspot.com',
    androidClientId: '287386333635-hp75q0lb33e7bd9kr5j8spsam36q55ln.apps.googleusercontent.com',
    iosClientId: '287386333635-docmlqusnr6t3nedi97llc2n6394nk90.apps.googleusercontent.com',
    iosBundleId: 'com.example.newShalongApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqmRHcvqYnGbp3jrYlAOW0ox24XgbsJv0',
    appId: '1:287386333635:web:625cc226cae6c3498e8d76',
    messagingSenderId: '287386333635',
    projectId: 'shalong-4a203',
    authDomain: 'shalong-4a203.firebaseapp.com',
    storageBucket: 'shalong-4a203.appspot.com',
    measurementId: 'G-N2DL5VB94F',
  );
}
